name: GameCore
author: gronnmann
version: 1.0
main: io.github.gronnmann.gamecore.GameCore
commands:
    fstart:
        description: Forces the game to start
    fstop:
        description: Forces the game to start