name: GameCore
author: gronnmann
version: 1.3
main: io.github.gronnmann.gamecore.Main
commands:
    fstart:
        description: Forces the game to start
    fstop:
        description: Forces the game to start
    setloc:
        description: Changes the lobby/spectatorspawn location